Adds cuda support
conda-forge/papi-feedstock pull request #5
Opened 2024-09-19 20:02 UTC by calebwherry

Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)

Adds `cuda` support.

2024-09-19 20:02 UTC, calebwherry commented
@conda-forge-admin, please rerender

2024-09-19 20:23 UTC, calebwherry commented
@apmorton This adds `cuda` support to the `papi` package. Description updated with all updates and reasons. Re-rendered as well.

2024-09-19 20:29 UTC, kkraus14 commented on recipe/meta.yaml
> +    - cuda-toolkit
This includes the entire cuda toolkit which I strongly suspect isn't needed here. Which cuda libraries are actually needed for linking? The cuda runtime and possibly cuda driver?

2024-09-19 20:30 UTC, mariusvniekerk commented on recipe/meta.yaml
> +    - cuda-toolkit
likely also nvml

2024-09-19 20:31 UTC, calebwherry commented on recipe/meta.yaml
> +    - cuda-toolkit
Ah, good call out. I can dwindle this down to smallest set of cuda libs needed.

2024-09-20 16:37 UTC, calebwherry commented
@conda-forge-admin, please rerender

2024-09-20 16:37 UTC, kkraus14 approved these changes

2024-09-20 16:39 UTC, calebwherry commented on recipe/meta.yaml
> +    - cuda-toolkit
Fixed. Turns out the issue I was having was because I didn't have `cuda-nvcc` set-up correctly. `cuda-toolkit` has been removed.

2024-09-21 06:58 UTC, calebwherry commented
@conda-forge-admin, please rerender

2024-09-21 07:08 UTC, calebwherry commented
@apmorton Alright, got the minimal set of cuda dependencies sorted out and everything re-rendered and green. Should be good to go for review now. Thanks!

2024-09-23 16:23 UTC, apmorton requested changes, later dismissed
Does papi now _require_ cuda?

If not, then we also need to do the nonsense required to get non-cuda builds published as well.

2024-09-23 16:23 UTC, apmorton commented on recipe/conda_build_config.yaml
> +  - '12.5'
does papi not support cuda 11?

I'd rather not pin cuda in this way - if it doesn't work with >12.5 can we add a `skip: true  # [cuda > 12.5]` directive instead?

2024-09-23 16:23 UTC, apmorton commented on recipe/meta.yaml
> +{% set version = "7.2.0b1" %}
should we wait until there is a non-beta release available?

2024-09-23 16:29 UTC, apmorton commented on recipe/meta.yaml
> +    - cuda-cupti-dev {{ cuda_version }}
Just noticed these are only build dependencies - perhaps this means we don't need cuda/nocuda variants?

I'm not all that familiar with the state of cuda infrastructure on conda-forge.

If this package is built with 12.5 will it work in runtime environments that get solved with:
- no cuda?
- cuda 11.x?
- cuda 13.x?

2024-09-24 14:50 UTC, calebwherry commented on recipe/meta.yaml
> +{% set version = "7.2.0b1" %}
It's been out for almost 8 months with no site on when a release will happen. But I agree, putting in a pre-release here doesn't make sense. I will create an 'rc' branch and open a new PR against that, following these instructions: https://conda-forge.org/docs/maintainer/knowledge_base/#pre-release-builds

2024-09-24 14:54 UTC, calebwherry commented on recipe/meta.yaml
> +    - cuda-cupti-dev {{ cuda_version }}
Yep, these are build only dependencies to enable support for loading the cuda components if it available at runtime. So if the runtime environment doesn't have the needed libs/device, cuda support is disabled. You can see this in action with `papi_component_avail`. I'll add that to the test portion so it spits out those details as well on the GHA runner.

As for versioning, nivida itself has interop guarantees between the cuda toolkit versions. So as long as nvidia doesn't break that guarantee, you can build with whatever toolkit you like and if the libraries are available at runtime, it will interop/jit/etc to fix issues it has.

2024-09-24 14:56 UTC, closed without merging

2024-09-24 14:56 UTC, calebwherry commented
@apmorton Thanks for the review! As stated in the comments, I'm going to close this PR and create an 'rc' branch to push this to since it is a release candidate and not an official release. Hopefully my comments also address you concerns of cuda being required (it isn't) and that there should be no issues with using this with different cuda toolkits and on systems that don't have support.

2024-09-24 15:07 UTC, calebwherry commented
Actually, @apmorton there has to be an already existing branch called `rc` for me to open a PR against. Can you create that for me so I can move this there? Super appreciate the help!

2024-09-24 16:11 UTC, apmorton commented
@calebwherry created